name: MasterBrewing
version: 1.0.0
main: com.supafloof.masterbrewing.MasterBrewing
api-version: 1.20
author: SupaFloof Games, LLC
description: Master Brewing Stands with unlimited potion upgrades

commands:
  masterbrewing:
    description: Master Brewing command
    usage: /masterbrewing <help|give|reload>
    aliases: [mb, mbrew]
  effects:
    description: Show all active potion effects
    usage: /effects
    aliases: [eff]

permissions:
  masterbrewing.use:
    description: Allows using the /masterbrewing command to open a virtual brewing stand
    default: false
  masterbrewing.give:
    description: Allows giving Master Brewing Stands
    default: op
  masterbrewing.admin:
    description: Allows reloading configuration
    default: op